name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  gem:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gem
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bundle exec rake test

  dummy:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    defaults:
      run:
        working-directory: dummy
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bin/rails db:prepare
      - run: bin/rails test
